# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default=10, max_length=300),
            preserve_default=False,
        ),
    ]
