# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-12 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genericviews', '0002_product_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='title',
            new_name='name',
        ),
    ]
